#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : pypi-flatten_json
Version  : 0.1.13
Release  : 25
URL      : https://files.pythonhosted.org/packages/cb/be/8f8e563004c7eae0b03be0fc6427a4ce07691c758250fdb31a9e934028d4/flatten_json-0.1.13.tar.gz
Source0  : https://files.pythonhosted.org/packages/cb/be/8f8e563004c7eae0b03be0fc6427a4ce07691c758250fdb31a9e934028d4/flatten_json-0.1.13.tar.gz
Summary  : Flatten JSON objects
Group    : Development/Tools
License  : MIT
Requires: pypi-flatten_json-bin = %{version}-%{release}
Requires: pypi-flatten_json-license = %{version}-%{release}
Requires: pypi-flatten_json-python = %{version}-%{release}
Requires: pypi-flatten_json-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3
Provides: flatten_json
Provides: flatten_json-python
Provides: flatten_json-python3
BuildRequires : pypi(six)

%description
# flatten_json
        Flattens JSON objects in Python. ```flatten_json``` flattens the hierarchy in your object which can be useful if you want to force your objects into a table.
        
        ## Installation
        ```bash
        pip install flatten_json
        ```
        
        ## flatten
        
        ### Usage

%package bin
Summary: bin components for the pypi-flatten_json package.
Group: Binaries
Requires: pypi-flatten_json-license = %{version}-%{release}

%description bin
bin components for the pypi-flatten_json package.


%package license
Summary: license components for the pypi-flatten_json package.
Group: Default

%description license
license components for the pypi-flatten_json package.


%package python
Summary: python components for the pypi-flatten_json package.
Group: Default
Requires: pypi-flatten_json-python3 = %{version}-%{release}

%description python
python components for the pypi-flatten_json package.


%package python3
Summary: python3 components for the pypi-flatten_json package.
Group: Default
Requires: python3-core
Provides: pypi(flatten_json)
Requires: pypi(six)

%description python3
python3 components for the pypi-flatten_json package.


%prep
%setup -q -n flatten_json-0.1.13
cd %{_builddir}/flatten_json-0.1.13

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1641436568
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=auto "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=auto "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/pypi-flatten_json
cp %{_builddir}/flatten_json-0.1.13/LICENSE %{buildroot}/usr/share/package-licenses/pypi-flatten_json/6a22ee80346cfa8d9b987f2381bc8c390cb04352
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/flatten_json

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/pypi-flatten_json/6a22ee80346cfa8d9b987f2381bc8c390cb04352

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
